name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: "."
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2004
          - ubuntu1804
          - debian10
          - debian9
    steps:
      - uses: actions/checkout@v2
      - name: molecule
        uses: robertdebock/molecule-action@2.6.8
